# Generated by Django 3.2 on 2023-06-20 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
